import RED_BAG_RAIN from "./RED_BAG_RAIN/index.vue";
import FIRST_DEPOSIT from "./FIRST_DEPOSIT.vue";
import SECOND_DEPOSIT from "./SECOND_DEPOSIT.vue";
import FREE_WHEEL from "./FREE_WHEEL/index.vue";
import ASSIGN_DAY from "./ASSIGN_DAY.vue";
import LOSS_IN_SPORTS from "./LOSS_IN_SPORTS.vue";
import RECHARGE_BONUS from "./RECHARGE_BONUS.vue";
import DAILY_COMPETITION from "./DAILY_COMPETITION.vue";
import SPIN_WHEEL from "./SPIN_WHEEL.vue";

export default {
	RED_BAG_RAIN,
	FIRST_DEPOSIT,
	SECOND_DEPOSIT,
	FREE_WHEEL,
	ASSIGN_DAY,
	LOSS_IN_SPORTS,
	RECHARGE_BONUS,
	DAILY_COMPETITION,
	SPIN_WHEEL,
};
