/** 窜关成功返回对象 */
const a = {
  "transId": 0,
  "sysTransId": 0,
  "luckyTransId": 0,
  "totalStake": 0,
  "maxBet": 0.0,
  "minBet": 0.0,
  "betStatus": 1,
  "parlayBetAcceptSec": 0,
  "parlayTicketStatus": null,
  "singleTickets": [],
  "currentCombos": [{
    "comboPrice": 253.492,
    "comboType": "Trebles",
    "stake": 1,
    "betCount": 4,
    "maxBet": 118.0,
    "abnormalMarketList": null
  }],
  "priceInfo": [{
    "stateCode": 0,
    "stateMessage": "Success",
    "currentPrice": 25.0,
    "marketId": 693972134,
    "key": "1",
    "sportType": 1,
    "point": 0.0,
    "betType": 5,
    "oddsType": 3,
    "status": "running",
    "liveHomeScore": 1,
    "liveAwayScore": 3
  }, {
    "stateCode": 0,
    "stateMessage": "Success",
    "currentPrice": 1.77,
    "marketId": 693972246,
    "key": "h",
    "sportType": 1,
    "point": 0.25,
    "betType": 1,
    "oddsType": 3,
    "status": "running",
    "liveHomeScore": 1,
    "liveAwayScore": 2
  }, {
    "stateCode": 6,
    "stateMessage": "Point is expired",
    "currentPrice": 1.66,
    "marketId": 693972375,
    "key": "h",
    "sportType": 1,
    "point": 2.25,
    "betType": 3,
    "oddsType": 3,
    "status": "running",
    "liveHomeScore": 0,
    "liveAwayScore": 0
  }, {
    "stateCode": 0,
    "stateMessage": "Success",
    "currentPrice": 2.03,
    "marketId": 693972667,
    "key": "h",
    "sportType": 1,
    "point": 1.75,
    "betType": 3,
    "oddsType": 3,
    "status": "running",
    "liveHomeScore": 0,
    "liveAwayScore": 0
  }]
}