const countryList = [
	{ countryName: 'Angola', code: 'AO' },
	{ countryName: 'Afghanistan', code: 'AF' },
	{ countryName: 'Albania', code: 'AL' },
	{ countryName: 'Algeria', code: 'DZ' },
	{ countryName: 'Andorra', code: 'AD' },
	{ countryName: 'Anguilla', code: 'AI' },
	{ countryName: 'Antigua and Barbuda', code: 'AG' },
	{ countryName: 'Argentina', code: 'AR' },
	{ countryName: 'Armenia', code: 'AM' },
	{ countryName: 'Ascension', code: ' ' },
	{ countryName: 'Australia', code: 'AU' },
	{ countryName: 'Austria', code: 'AT' },
	{ countryName: 'Azerbaijan', code: 'AZ' },
	{ countryName: 'Bahamas', code: 'BS' },
	{ countryName: 'Bahrain', code: 'BH' },
	{ countryName: 'Bangladesh', code: 'BD' },
	{ countryName: 'Barbados', code: 'BB' },
	{ countryName: 'Belarus', code: 'BY' },
	{ countryName: 'Belgium', code: 'BE' },
	{ countryName: 'Belize', code: 'BZ' },
	{ countryName: 'Benin', code: 'BJ' },
	{ countryName: 'Bermuda Is.', code: 'BM' },
	{ countryName: 'Bolivia', code: 'BO' },
	{ countryName: 'Botswana', code: 'BW' },
	{ countryName: 'Brazil', code: 'BR' },
	{ countryName: 'Brunei', code: 'BN' },
	{ countryName: 'Bulgaria', code: 'BG' },
	{ countryName: 'Burkina-faso', code: 'BF' },
	{ countryName: 'Burma', code: 'MM' },
	{ countryName: 'Burundi', code: 'BI' },
	{ countryName: 'Cameroon', code: 'CM' },
	{ countryName: 'Canada', code: 'CA' },
	{ countryName: 'Cayman Is.', code: ' ' },
	{ countryName: 'Central African Republic', code: 'CF' },
	{ countryName: 'Chad', code: 'TD' },
	{ countryName: 'Chile', code: 'CL' },
	{ countryName: 'China', code: 'CN' },
	{ countryName: 'Colombia', code: 'CO' },
	{ countryName: 'Congo', code: 'CG' },
	{ countryName: 'Cook Is.', code: 'CK' },
	{ countryName: 'Costa Rica', code: 'CR' },
	{ countryName: 'Cuba', code: 'CU' },
	{ countryName: 'Cyprus', code: 'CY' },
	{ countryName: 'Czech Republic', code: 'CZ' },
	{ countryName: 'Denmark', code: 'DK' },
	{ countryName: 'Djibouti', code: 'DJ' },
	{ countryName: 'Dominica Rep', code: 'DO' },
	{ countryName: 'Ecuador', code: 'EC' },
	{ countryName: 'Egypt', code: 'EG' },
	{ countryName: 'EI Salvador', code: 'SV' },
	{ countryName: 'Estonia', code: 'EE' },
	{ countryName: 'Ethiopia', code: 'ET' },
	{ countryName: 'Fiji', code: 'FJ' },
	{ countryName: 'Finland', code: 'FI' },
	{ countryName: 'France', code: 'FR' },
	{ countryName: 'French Guiana', code: 'GF' },
	{ countryName: 'Gabon', code: 'GA' },
	{ countryName: 'Gambia', code: 'GM' },
	{ countryName: 'Georgia', code: 'GE' },
	{ countryName: 'Germany', code: 'DE' },
	{ countryName: 'Ghana', code: 'GH' },
	{ countryName: 'Gibraltar', code: 'GI' },
	{ countryName: 'Greece', code: 'GR' },
	{ countryName: 'Grenada', code: 'GD' },
	{ countryName: 'Guam', code: 'GU' },
	{ countryName: 'Guatemala', code: 'GT' },
	{ countryName: 'Guinea', code: 'GN' },
	{ countryName: 'Guyana', code: 'GY' },
	{ countryName: 'Haiti', code: 'HT' },
	{ countryName: 'Honduras', code: 'HN' },
	{ countryName: 'Hongkong', code: 'HK' },
	{ countryName: 'Hungary', code: 'HU' },
	{ countryName: 'Iceland', code: 'IS' },
	{ countryName: 'India', code: 'IN' },
	{ countryName: 'Indonesia', code: 'ID' },
	{ countryName: 'Iran', code: 'IR' },
	{ countryName: 'Iraq', code: 'IQ' },
	{ countryName: 'Ireland', code: 'IE' },
	{ countryName: 'Israel', code: 'IL' },
	{ countryName: 'Italy', code: 'IT' },
	{ countryName: 'Ivory Coast', code: ' ' },
	{ countryName: 'Jamaica', code: 'JM' },
	{ countryName: 'Japan', code: 'JP' },
	{ countryName: 'Jordan', code: 'JO' },
	{ countryName: 'Kampuchea (Cambodia )', code: 'KH' },
	{ countryName: 'Kazakstan', code: 'KZ' },
	{ countryName: 'Kenya', code: 'KE' },
	{ countryName: 'Korea', code: 'KR' },
	{ countryName: 'Kuwait', code: 'KW' },
	{ countryName: 'Kyrgyzstan', code: 'KG' },
	{ countryName: 'Laos', code: 'LA' },
	{ countryName: 'Latvia', code: 'LV' },
	{ countryName: 'Lebanon', code: 'LB' },
	{ countryName: 'Lesotho', code: 'LS' },
	{ countryName: 'Liberia', code: 'LR' },
	{ countryName: 'Libya', code: 'LY' },
	{ countryName: 'Liechtenstein', code: 'LI' },
	{ countryName: 'Lithuania', code: 'LT' },
	{ countryName: 'Luxembourg', code: 'LU' },
	{ countryName: 'Macao', code: 'MO' },
	{ countryName: 'Madagascar', code: 'MG' },
	{ countryName: 'Malawi', code: 'MW' },
	{ countryName: 'Malaysia', code: 'MY' },
	{ countryName: 'Maldives', code: 'MV' },
	{ countryName: 'Mali', code: 'ML' },
	{ countryName: 'Malta', code: 'MT' },
	{ countryName: 'Mariana Is', code: ' ' },
	{ countryName: 'Martinique', code: ' ' },
	{ countryName: 'Mauritius', code: 'MU' },
	{ countryName: 'Mexico', code: 'MX' },
	{ countryName: 'Moldova', code: 'Republic of' },
	{ countryName: 'Monaco', code: 'MC' },
	{ countryName: 'Mongolia', code: 'MN' },
	{ countryName: 'Montserrat Is', code: 'MS' },
	{ countryName: 'Morocco', code: 'MA' },
	{ countryName: 'Mozambique', code: 'MZ' },
	{ countryName: 'Namibia', code: 'NA' },
	{ countryName: 'Nauru', code: 'NR' },
	{ countryName: 'Nepal', code: 'NP' },
	{ countryName: 'Netheriands Antilles', code: ' ' },
	{ countryName: 'Netherlands', code: 'NL' },
	{ countryName: 'New Zealand', code: 'NZ' },
	{ countryName: 'Nicaragua', code: 'NI' },
	{ countryName: 'Niger', code: 'NE' },
	{ countryName: 'Nigeria', code: 'NG' },
	{ countryName: 'North Korea', code: 'KP' },
	{ countryName: 'Norway', code: 'NO' },
	{ countryName: 'Oman', code: 'OM' },
	{ countryName: 'Pakistan', code: 'PK' },
	{ countryName: 'Panama', code: 'PA' },
	{ countryName: 'Papua New Cuinea' },
	{ countryName: 'Paraguay', code: 'PY' },
	{ countryName: 'Peru', code: 'PE' },
	{ countryName: 'Philippines', code: 'PH' },
	{ countryName: 'Poland', code: 'PL' },
	{ countryName: 'French Polynesia' },
	{ countryName: 'Portugal', code: 'PT' },
	{ countryName: 'Puerto Rico', code: 'PR' },
	{ countryName: 'Qatar', code: 'QA' },
	{ countryName: 'Reunion', code: ' ' },
	{ countryName: 'Romania', code: 'RO' },
	{ countryName: 'Russia', code: 'RU' },
	{ countryName: 'Saint Lueia', code: 'LC' },
	{ countryName: 'Saint Vincent', code: 'VC' },
	{ countryName: 'Samoa Eastern', code: '' },
	{ countryName: 'Samoa Western', code: '' },
	{ countryName: 'San Marino', code: 'SM' },
	{ countryName: 'Sao Tome and Principe', code: 'ST' },
	{ countryName: 'Saudi Arabia', code: 'SA' },
	{ countryName: 'Senegal', code: 'SN' },
	{ countryName: 'Seychelles', code: 'SC' },
	{ countryName: 'Sierra Leone', code: 'SL' },
	{ countryName: 'Singapore', code: 'SG' },
	{ countryName: 'Slovakia', code: 'SK' },
	{ countryName: 'Slovenia', code: 'SI' },
	{ countryName: 'Solomon Is', code: 'SB' },
	{ countryName: 'Somali', code: 'SO' },
	{ countryName: 'South Africa', code: 'ZA' },
	{ countryName: 'Spain', code: 'ES' },
	{ countryName: 'Sri Lanka', code: 'LK' },
	{ countryName: 'St.Lucia', code: 'LC' },
	{ countryName: 'St.Vincent', code: 'VC' },
	{ countryName: 'Sudan', code: 'SD' },
	{ countryName: 'Suriname', code: 'SR' },
	{ countryName: 'Swaziland', code: 'SZ' },
	{ countryName: 'Sweden', code: 'SE' },
	{ countryName: 'Switzerland', code: 'CH' },
	{ countryName: 'Syria', code: 'SY' },
	{ countryName: 'Taiwan', code: 'TW' },
	{ countryName: 'Tajikstan', code: 'TJ' },
	{ countryName: 'Tanzania', code: 'TZ' },
	{ countryName: 'Thailand', code: 'TH' },
	{ countryName: 'Togo', code: 'TG' },
	{ countryName: 'Tonga', code: 'TO' },
	{ countryName: 'Trinidad and Tobago', code: 'TT' },
	{ countryName: 'Tunisia', code: 'TN' },
	{ countryName: 'Turkey', code: 'TR' },
	{ countryName: 'Turkmenistan', code: 'TM' },
	{ countryName: 'Uganda', code: 'UG' },
	{ countryName: 'Ukraine', code: 'UA' },
	{ countryName: 'United Arab Emirates', code: 'AE' },
	{ countryName: 'United Kiongdom', code: 'GB' },
	{ countryName: 'United States of America', code: 'US' },
	{ countryName: 'Uruguay', code: 'UY' },
	{ countryName: 'Uzbekistan', code: 'UZ' },
	{ countryName: 'Venezuela', code: 'VE' },
	{ countryName: 'Vietnam', code: 'VN' },
	{ countryName: 'Yemen', code: 'YE' },
	{ countryName: 'Yugoslavia', code: 'YU' },
	{ countryName: 'Zimbabwe', code: 'ZW' },
	{ countryName: 'Zaire', code: 'ZR' },
	{ countryName: 'Zambia', code: 'ZM' },
];

export default countryList;
