import { LotteryPlayGroup } from "/@/views/lottery/types/lottery";

/**
 * @description PK10 静态玩法配置
 * @author Hida
 * @description 特殊玩法 需要配置 gamePlayCode 用于匹配玩法，isSpecialPlay走特殊玩法逻辑 对应数据会直接返回不做投注项处理
 */
export const gameplayList: LotteryPlayGroup[] = [
	{
		id: "1",
		gamePlayName: "冠亚军和",
		type: "selectBallLine",
		isSpecialPlay: true,
		gamePlayCodes: ["smp_gyjh_dxds", "smp_gyh3d19"],
		desc: "冠亚和大小：开奖号码中冠军与亚军之和>11为“大”，≤11为“小”<br />冠亚和单双：开奖号码中冠军与亚军之和的个位数为1、3、5、7、9为“单”，0、2、4、6、8为“双”",
		actived: false,
		oddsList: [
			{
				title: "大",
				desc: "开奖号码中冠军与亚军之和>11为“大”",
				actived: false,
				optionCode: "大",
			},
			{
				title: "小",
				desc: "开奖号码中冠军与亚军之和≤11为“小”",
				actived: false,
				optionCode: "小",
			},
			{
				title: "单",
				desc: "开奖号码中冠军与亚军之和的个位数为1、3、5、7、9为“单”",
				actived: false,
				optionCode: "单",
			},
			{
				title: "双",
				desc: "开奖号码中冠军与亚军之和的个位数为0、2、4、6、8为“双”",
				actived: false,
				optionCode: "双",
			},
			{
				type: "selectBallLine",
				title: "选择球",
				selectBallDesc: "选择1个数值，与开奖号码中冠军、亚军的2个号码之和相同，即中奖<br />举例：开奖号码1, 2,*,*,*,*,*,*,*,*，投注「3」，即中奖",
				actived: false,
				gamePlayCode: "smp_gyh3d19",
				isSpecialPlay: true,
			},
		],
	},
	{
		id: "2",
		gamePlayName: "冠军",
		gamePlayCodes: ["smp_zhgj", "smp_d1d10gj"],
		desc: "投注一种属性，投注的属性与该位置的开奖号码属性相同时，即中奖<br />大小：开奖号码≥6为“大”，≤5为“小”<br />单双：开奖号码个位数为1、3、5、7、9为“单”，0、2、4、6、8为“双”<br />选球：选择1个球为1注。所选号码与该位置上的开奖号码一致，即中奖",
		actived: false,
		oddsList: [
			{
				title: "大",
				desc: "开奖号码≥6为“大”",
				actived: false,
				optionCode: "大",
			},
			{
				title: "小",
				desc: "开奖号码≤5为“小”",
				actived: false,
				optionCode: "小",
			},
			{
				title: "单",
				desc: "开奖号码个位数为1、3、5、7、9为“单”",
				actived: false,
				optionCode: "单",
			},
			{
				title: "双",
				desc: "开奖号码个位数为0、2、4、6、8为“双”",
				actived: false,
				optionCode: "双",
			},
			{
				id: 1,
				type: "selectBall",
				title: "选号",
				actived: false,
				gamePlayCode: "smp_d1d10gj",
				isSpecialPlay: true,
				ballNum: 10,
				maxBet: 1,
			},
		],
	},
	{
		id: "3",
		gamePlayName: "亚军",
		gamePlayCodes: ["smp_zhyj", "smp_d1d10yj"],
		desc: "投注一种属性，投注的属性与该位置的开奖号码属性相同时，即中奖<br />大小：开奖号码≥6为“大”，≤5为“小”<br />单双：开奖号码个位数为1、3、5、7、9为“单”，0、2、4、6、8为“双”<br />选球：选择1个球为1注。所选号码与该位置上的开奖号码一致，即中奖",
		actived: false,
		oddsList: [
			{
				title: "大",
				desc: "开奖号码≥6为“大”",
				actived: false,
				optionCode: "大",
			},
			{
				title: "小",
				desc: "开奖号码≤5为“小”",
				actived: false,
				optionCode: "小",
			},
			{
				title: "单",
				desc: "开奖号码个位数为1、3、5、7、9为“单”",
				actived: false,
				optionCode: "单",
			},
			{
				title: "双",
				desc: "开奖号码个位数为0、2、4、6、8为“双”",
				actived: false,
				optionCode: "双",
			},
			{
				id: 1,
				type: "selectBall",
				title: "选号",
				actived: false,
				gamePlayCode: "smp_d1d10yj",
				isSpecialPlay: true,
				ballNum: 10,
				maxBet: 1,
			},
		],
	},
	{
		id: "4",
		gamePlayName: "第三名",
		gamePlayCodes: ["smp_zhd3m", "smp_d1d10d3m"],
		desc: "投注一种属性，投注的属性与该位置的开奖号码属性相同时，即中奖<br />大小：开奖号码≥6为“大”，≤5为“小”<br />单双：开奖号码个位数为1、3、5、7、9为“单”，0、2、4、6、8为“双”<br />选球：选择1个球为1注。所选号码与该位置上的开奖号码一致，即中奖",
		actived: false,
		oddsList: [
			{
				title: "大",
				desc: "开奖号码≥6为“大”",
				actived: false,
				optionCode: "大",
			},
			{
				title: "小",
				desc: "开奖号码≤5为“小”",
				actived: false,
				optionCode: "小",
			},
			{
				title: "单",
				desc: "开奖号码个位数为1、3、5、7、9为“单”",
				actived: false,
				optionCode: "单",
			},
			{
				title: "双",
				desc: "开奖号码个位数为0、2、4、6、8为“双”",
				actived: false,
				optionCode: "双",
			},
			{
				id: 1,
				type: "selectBall",
				title: "选号",
				actived: false,
				gamePlayCode: "smp_d1d10d3m",
				isSpecialPlay: true,
				ballNum: 10,
				maxBet: 1,
			},
		],
	},
	{
		id: "5",
		gamePlayName: "第四名",
		gamePlayCodes: ["smp_zhd4m", "smp_d1d10d4m"],
		desc: "投注一种属性，投注的属性与该位置的开奖号码属性相同时，即中奖<br />大小：开奖号码≥6为“大”，≤5为“小”<br />单双：开奖号码个位数为1、3、5、7、9为“单”，0、2、4、6、8为“双”<br />选球：选择1个球为1注。所选号码与该位置上的开奖号码一致，即中奖",
		actived: false,
		oddsList: [
			{
				title: "大",
				desc: "选择大数",
				actived: false,
				optionCode: "大",
			},
			{
				title: "小",
				desc: "选择小数",
				actived: false,
				optionCode: "小",
			},
			{
				title: "单",
				desc: "选择单数",
				actived: false,
				optionCode: "单",
			},
			{
				title: "双",
				desc: "选择双数",
				actived: false,
				optionCode: "双",
			},
			{
				id: 1,
				type: "selectBall",
				title: "选号",
				actived: false,
				gamePlayCode: "smp_d1d10d4m",
				isSpecialPlay: true,
				ballNum: 10,
				maxBet: 1,
			},
		],
	},
	{
		id: "6",
		gamePlayName: "第五名",
		gamePlayCodes: ["smp_zhd5m", "smp_d1d10d5m"],
		desc: "投注一种属性，投注的属性与该位置的开奖号码属性相同时，即中奖<br />大小：开奖号码≥6为“大”，≤5为“小”<br />单双：开奖号码个位数为1、3、5、7、9为“单”，0、2、4、6、8为“双”<br />选球：选择1个球为1注。所选号码与该位置上的开奖号码一致，即中奖",
		actived: false,
		oddsList: [
			{
				title: "大",
				desc: "选择大数",
				actived: false,
				optionCode: "大",
			},
			{
				title: "小",
				desc: "选择小数",
				actived: false,
				optionCode: "小",
			},
			{
				title: "单",
				desc: "选择单数",
				actived: false,
				optionCode: "单",
			},
			{
				title: "双",
				desc: "选择双数",
				actived: false,
				optionCode: "双",
			},
			{
				id: 1,
				type: "selectBall",
				title: "选号",
				actived: false,
				gamePlayCode: "smp_d1d10d5m",
				isSpecialPlay: true,
				ballNum: 10,
				maxBet: 1,
			},
		],
	},
	{
		id: "7",
		gamePlayName: "第六名",
		gamePlayCodes: ["smp_zhd6m", "smp_d1d10d6m"],
		desc: "投注一种属性，投注的属性与该位置的开奖号码属性相同时，即中奖<br />大小：开奖号码≥6为“大”，≤5为“小”<br />单双：开奖号码个位数为1、3、5、7、9为“单”，0、2、4、6、8为“双”<br />选球：选择1个球为1注。所选号码与该位置上的开奖号码一致，即中奖",
		actived: false,
		oddsList: [
			{
				title: "大",
				desc: "选择大数",
				actived: false,
				optionCode: "大",
			},
			{
				title: "小",
				desc: "选择小数",
				actived: false,
				optionCode: "小",
			},
			{
				title: "单",
				desc: "选择单数",
				actived: false,
				optionCode: "单",
			},
			{
				title: "双",
				desc: "选择双数",
				actived: false,
				optionCode: "双",
			},
			{
				id: 1,
				type: "selectBall",
				title: "选号",
				actived: false,
				gamePlayCode: "smp_d1d10d6m",
				isSpecialPlay: true,
				ballNum: 10,
				maxBet: 1,
			},
		],
	},
	{
		id: "8",
		gamePlayName: "第七名",
		gamePlayCodes: ["smp_zhd7m", "smp_d1d10d7m"],
		desc: "投注一种属性，投注的属性与该位置的开奖号码属性相同时，即中奖<br />大小：开奖号码≥6为“大”，≤5为“小”<br />单双：开奖号码个位数为1、3、5、7、9为“单”，0、2、4、6、8为“双”<br />选球：选择1个球为1注。所选号码与该位置上的开奖号码一致，即中奖",
		actived: false,
		oddsList: [
			{
				title: "大",
				desc: "选择大数",
				actived: false,
				optionCode: "大",
			},
			{
				title: "小",
				desc: "选择小数",
				actived: false,
				optionCode: "小",
			},
			{
				title: "单",
				desc: "选择单数",
				actived: false,
				optionCode: "单",
			},
			{
				title: "双",
				desc: "选择双数",
				actived: false,
				optionCode: "双",
			},
			{
				id: 1,
				type: "selectBall",
				title: "选号",
				actived: false,
				gamePlayCode: "smp_d1d10d7m",
				isSpecialPlay: true,
				ballNum: 10,
				maxBet: 1,
			},
		],
	},
	{
		id: "9",
		gamePlayName: "第八名",
		gamePlayCodes: ["smp_zhd8m", "smp_d1d10d8m"],
		desc: "投注一种属性，投注的属性与该位置的开奖号码属性相同时，即中奖<br />大小：开奖号码≥6为“大”，≤5为“小”<br />单双：开奖号码个位数为1、3、5、7、9为“单”，0、2、4、6、8为“双”<br />选球：选择1个球为1注。所选号码与该位置上的开奖号码一致，即中奖",
		actived: false,
		oddsList: [
			{
				title: "大",
				desc: "选择大数",
				actived: false,
				optionCode: "大",
			},
			{
				title: "小",
				desc: "选择小数",
				actived: false,
				optionCode: "小",
			},
			{
				title: "单",
				desc: "选择单数",
				actived: false,
				optionCode: "单",
			},
			{
				title: "双",
				desc: "选择双数",
				actived: false,
				optionCode: "双",
			},
			{
				id: 1,
				type: "selectBall",
				title: "选号",
				actived: false,
				gamePlayCode: "smp_d1d10d8m",
				isSpecialPlay: true,
				ballNum: 10,
				maxBet: 1,
			},
		],
	},
	{
		id: "10",
		gamePlayName: "第九名",
		gamePlayCodes: ["smp_zhd9m", "smp_d1d10d9m"],
		desc: "投注一种属性，投注的属性与该位置的开奖号码属性相同时，即中奖<br />大小：开奖号码≥6为“大”，≤5为“小”<br />单双：开奖号码个位数为1、3、5、7、9为“单”，0、2、4、6、8为“双”<br />选球：选择1个球为1注。所选号码与该位置上的开奖号码一致，即中奖",
		actived: false,
		oddsList: [
			{
				title: "大",
				desc: "选择大数",
				actived: false,
				optionCode: "大",
			},
			{
				title: "小",
				desc: "选择小数",
				actived: false,
				optionCode: "小",
			},
			{
				title: "单",
				desc: "选择单数",
				actived: false,
				optionCode: "单",
			},
			{
				title: "双",
				desc: "选择双数",
				actived: false,
				optionCode: "双",
			},
			{
				id: 1,
				type: "selectBall",
				title: "选号",
				actived: false,
				gamePlayCode: "smp_d1d10d9m",
				isSpecialPlay: true,
				ballNum: 10,
				maxBet: 1,
			},
		],
	},
	{
		id: "11",
		gamePlayName: "第十名",
		gamePlayCodes: ["smp_zhd10m", "smp_d1d10d10m"],
		desc: "投注一种属性，投注的属性与该位置的开奖号码属性相同时，即中奖<br />大小：开奖号码≥6为“大”，≤5为“小”<br />单双：开奖号码个位数为1、3、5、7、9为“单”，0、2、4、6、8为“双”<br />选球：选择1个球为1注。所选号码与该位置上的开奖号码一致，即中奖",
		actived: false,
		oddsList: [
			{
				title: "大",
				desc: "选择大数",
				actived: false,
				optionCode: "大",
			},
			{
				title: "小",
				desc: "选择小数",
				actived: false,
				optionCode: "小",
			},
			{
				title: "单",
				desc: "选择单数",
				actived: false,
				optionCode: "单",
			},
			{
				title: "双",
				desc: "选择双数",
				actived: false,
				optionCode: "双",
			},
			{
				id: 1,
				type: "selectBall",
				title: "选号",
				actived: false,
				gamePlayCode: "smp_d1d10d10m",
				isSpecialPlay: true,
				ballNum: 10,
				maxBet: 1,
			},
		],
	},
] as unknown as LotteryPlayGroup[];
