import { SELECT_BALL, SELECT_BALL_LINE } from "/@/views/lottery/constant/index";
import { type GameplayList } from "/@/views/lottery/types/index";
import { generateBalls } from "/@/views/lottery/utils/generateBalls";

/**
 * @description PK10 静态玩法配置
 * @author Hida
 * @description 特殊玩法 需要配置 gamePlayCode 用于匹配玩法，isSpecialPlay走特殊玩法逻辑 对应数据会直接返回不做投注项处理
 */
export const gameplayList: GameplayList = [
	{
		id: "1",
		gamePlayName: "冠亚军和",
		gamePlayCodes: ["smp_gyjh_dxds", "smp_gyh3d19"],
		desc: "冠亚和大小：开奖号码中冠军与亚军之和>11为“大”，≤11为“小”<br />冠亚和单双：开奖号码中冠军与亚军之和的个位数为1、3、5、7、9为“单”，0、2、4、6、8为“双”",
		actived: false,
		oddsList: [
			{
				id: "1-1",
				itemOdds: "1.995",
				title: "大",
				desc: "开奖号码中冠军与亚军之和>11为“大”",
				actived: false,
				optionCode: "大",
			},
			{
				id: "1-2",
				itemOdds: "1.995",
				title: "小",
				desc: "开奖号码中冠军与亚军之和≤11为“小”",
				actived: false,
				optionCode: "小",
			},
			{
				id: "1-3",
				itemOdds: "1.995",
				title: "单",
				desc: "开奖号码中冠军与亚军之和的个位数为1、3、5、7、9为“单”",
				actived: false,
				optionCode: "单",
			},
			{
				id: "1-4",
				itemOdds: "1.995",
				title: "双",
				desc: "开奖号码中冠军与亚军之和的个位数为0、2、4、6、8为“双”",
				actived: false,
				optionCode: "双",
			},
			{
				id: "1-5",
				itemOdds: "1.995",
				title: "选择球",
				desc: "选选择1个数值，与开奖号码中冠军、亚军的2个号码之和相同，即中奖<br />举例：开奖号码1, 2,*,*,*,*,*,*,*,*，投注「3」，即中奖",
				actived: false,
				optionCode: "0",
				type: SELECT_BALL_LINE,
				children: generateBalls({ length: 17, hasZero: false, startIndex: 3 }),
			},
		],
	},
	{
		id: "2",
		gamePlayName: "冠军",
		gamePlayCodes: ["smp_zhgj", "smp_d1d10gj"],
		desc: "投注一种属性，投注的属性与该位置的开奖号码属性相同时，即中奖<br />大小：开奖号码≥6为“大”，≤5为“小”<br />单双：开奖号码个位数为1、3、5、7、9为“单”，0、2、4、6、8为“双”<br />选球：选择1个球为1注。所选号码与该位置上的开奖号码一致，即中奖",
		actived: false,
		oddsList: [
			{
				id: "2-1",
				itemOdds: "1.995",
				title: "大",
				desc: "开奖号码≥6为“大”",
				actived: false,
				optionCode: "大",
			},
			{
				id: "2-2",
				itemOdds: "1.995",
				title: "小",
				desc: "开奖号码≤5为“小”",
				actived: false,
				optionCode: "小",
			},
			{
				id: "2-3",
				itemOdds: "1.995",
				title: "单",
				desc: "开奖号码个位数为1、3、5、7、9为“单”",
				actived: false,
				optionCode: "单",
			},
			{
				id: "2-4",
				itemOdds: "1.995",
				title: "双",
				desc: "开奖号码个位数为0、2、4、6、8为“双”",
				actived: false,
				optionCode: "双",
			},
			{
				id: "2-5",
				itemOdds: "1.995",
				title: "选择球",
				desc: "",
				actived: false,
				optionCode: "0",
				type: SELECT_BALL,
				children: generateBalls({ length: 10, hasZero: false, startIndex: 1 }),
			},
		],
	},
	{
		id: "3",
		gamePlayName: "亚军",
		gamePlayCodes: ["smp_zhyj", "smp_d1d10yj"],
		desc: "投注一种属性，投注的属性与该位置的开奖号码属性相同时，即中奖<br />大小：开奖号码≥6为“大”，≤5为“小”<br />单双：开奖号码个位数为1、3、5、7、9为“单”，0、2、4、6、8为“双”<br />选球：选择1个球为1注。所选号码与该位置上的开奖号码一致，即中奖",
		actived: false,
		oddsList: [
			{
				id: "3-1",
				itemOdds: "1.995",
				title: "大",
				desc: "开奖号码≥6为“大”",
				actived: false,
				optionCode: "大",
			},
			{
				id: "3-2",
				itemOdds: "1.995",
				title: "小",
				desc: "开奖号码≤5为“小”",
				actived: false,
				optionCode: "小",
			},
			{
				id: "3-3",
				itemOdds: "1.995",
				title: "单",
				desc: "开奖号码个位数为1、3、5、7、9为“单”",
				actived: false,
				optionCode: "单",
			},
			{
				id: "3-4",
				itemOdds: "1.995",
				title: "双",
				desc: "开奖号码个位数为0、2、4、6、8为“双”",
				actived: false,
				optionCode: "双",
			},
			{
				id: "3-5",
				itemOdds: "1.995",
				title: "选择球",
				desc: "",
				actived: false,
				optionCode: "0",
				type: SELECT_BALL,
				children: generateBalls({ length: 10, hasZero: false, startIndex: 1 }),
			},
		],
	},
	{
		id: "4",
		gamePlayName: "第三名",
		gamePlayCodes: ["smp_zhd3m", "smp_d1d10d3m"],
		desc: "投注一种属性，投注的属性与该位置的开奖号码属性相同时，即中奖<br />大小：开奖号码≥6为“大”，≤5为“小”<br />单双：开奖号码个位数为1、3、5、7、9为“单”，0、2、4、6、8为“双”<br />选球：选择1个球为1注。所选号码与该位置上的开奖号码一致，即中奖",
		actived: false,
		oddsList: [
			{
				id: "4-1",
				itemOdds: "1.995",
				title: "大",
				desc: "开奖号码≥6为“大”",
				actived: false,
				optionCode: "大",
			},
			{
				id: "4-2",
				itemOdds: "1.995",
				title: "小",
				desc: "开奖号码≤5为“小”",
				actived: false,
				optionCode: "小",
			},
			{
				id: "4-3",
				itemOdds: "1.995",
				title: "单",
				desc: "开奖号码个位数为1、3、5、7、9为“单”",
				actived: false,
				optionCode: "单",
			},
			{
				id: "4-4",
				itemOdds: "1.995",
				title: "双",
				desc: "开奖号码个位数为0、2、4、6、8为“双”",
				actived: false,
				optionCode: "双",
			},
			{
				id: "4-5",
				itemOdds: "1.995",
				title: "选择球",
				desc: "",
				actived: false,
				optionCode: "0",
				type: SELECT_BALL,
				children: generateBalls({ length: 10, hasZero: false, startIndex: 1 }),
			},
		],
	},
	{
		id: "5",
		gamePlayName: "第四名",
		gamePlayCodes: ["smp_zhd4m", "smp_d1d10d4m"],
		desc: "投注一种属性，投注的属性与该位置的开奖号码属性相同时，即中奖<br />大小：开奖号码≥6为“大”，≤5为“小”<br />单双：开奖号码个位数为1、3、5、7、9为“单”，0、2、4、6、8为“双”<br />选球：选择1个球为1注。所选号码与该位置上的开奖号码一致，即中奖",
		actived: false,
		oddsList: [
			{
				id: "5-1",
				itemOdds: "1.995",
				title: "大",
				desc: "选择大数",
				actived: false,
				optionCode: "大",
			},
			{
				id: "5-2",
				itemOdds: "1.995",
				title: "小",
				desc: "选择小数",
				actived: false,
				optionCode: "小",
			},
			{
				id: "5-3",
				itemOdds: "1.995",
				title: "单",
				desc: "选择单数",
				actived: false,
				optionCode: "单",
			},
			{
				id: "5-4",
				itemOdds: "1.995",
				title: "双",
				desc: "选择双数",
				actived: false,
				optionCode: "双",
			},
			{
				id: "5-5",
				itemOdds: "1.995",
				title: "选择球",
				desc: "",
				actived: false,
				optionCode: "0",
				type: SELECT_BALL,
				children: generateBalls({ length: 10, hasZero: false, startIndex: 1 }),
			},
		],
	},
	{
		id: "6",
		gamePlayName: "第五名",
		gamePlayCodes: ["smp_zhd5m", "smp_d1d10d5m"],
		desc: "投注一种属性，投注的属性与该位置的开奖号码属性相同时，即中奖<br />大小：开奖号码≥6为“大”，≤5为“小”<br />单双：开奖号码个位数为1、3、5、7、9为“单”，0、2、4、6、8为“双”<br />选球：选择1个球为1注。所选号码与该位置上的开奖号码一致，即中奖",
		actived: false,
		oddsList: [
			{
				id: "6-1",
				itemOdds: "1.995",
				title: "大",
				desc: "选择大数",
				actived: false,
				optionCode: "大",
			},
			{
				id: "6-2",
				itemOdds: "1.995",
				title: "小",
				desc: "选择小数",
				actived: false,
				optionCode: "小",
			},
			{
				id: "6-3",
				itemOdds: "1.995",
				title: "单",
				desc: "选择单数",
				actived: false,
				optionCode: "单",
			},
			{
				id: "6-4",
				itemOdds: "1.995",
				title: "双",
				desc: "选择双数",
				actived: false,
				optionCode: "双",
			},
			{
				id: "6-5",
				itemOdds: "1.995",
				title: "选择球",
				desc: "",
				actived: false,
				optionCode: "0",
				type: SELECT_BALL,
				children: generateBalls({ length: 10, hasZero: false, startIndex: 1 }),
			},
		],
	},
	{
		id: "7",
		gamePlayName: "第六名",
		gamePlayCodes: ["smp_zhd6m", "smp_d1d10d6m"],
		desc: "投注一种属性，投注的属性与该位置的开奖号码属性相同时，即中奖<br />大小：开奖号码≥6为“大”，≤5为“小”<br />单双：开奖号码个位数为1、3、5、7、9为“单”，0、2、4、6、8为“双”<br />选球：选择1个球为1注。所选号码与该位置上的开奖号码一致，即中奖",
		actived: false,
		oddsList: [
			{
				id: "7-1",
				itemOdds: "1.995",
				title: "大",
				desc: "选择大数",
				actived: false,
				optionCode: "大",
			},
			{
				id: "7-2",
				itemOdds: "1.995",
				title: "小",
				desc: "选择小数",
				actived: false,
				optionCode: "小",
			},
			{
				id: "7-3",
				itemOdds: "1.995",
				title: "单",
				desc: "选择单数",
				actived: false,
				optionCode: "单",
			},
			{
				id: "7-4",
				itemOdds: "1.995",
				title: "双",
				desc: "选择双数",
				actived: false,
				optionCode: "双",
			},
			{
				id: "7-5",
				itemOdds: "1.995",
				title: "选择球",
				desc: "",
				actived: false,
				optionCode: "0",
				type: SELECT_BALL,
				children: generateBalls({ length: 10, hasZero: false, startIndex: 1 }),
			},
		],
	},
	{
		id: "8",
		gamePlayName: "第七名",
		gamePlayCodes: ["smp_zhd7m", "smp_d1d10d7m"],
		desc: "投注一种属性，投注的属性与该位置的开奖号码属性相同时，即中奖<br />大小：开奖号码≥6为“大”，≤5为“小”<br />单双：开奖号码个位数为1、3、5、7、9为“单”，0、2、4、6、8为“双”<br />选球：选择1个球为1注。所选号码与该位置上的开奖号码一致，即中奖",
		actived: false,
		oddsList: [
			{
				id: "8-1",
				itemOdds: "1.995",
				title: "大",
				desc: "选择大数",
				actived: false,
				optionCode: "大",
			},
			{
				id: "8-2",
				itemOdds: "1.995",
				title: "小",
				desc: "选择小数",
				actived: false,
				optionCode: "小",
			},
			{
				id: "8-3",
				itemOdds: "1.995",
				title: "单",
				desc: "选择单数",
				actived: false,
				optionCode: "单",
			},
			{
				id: "8-4",
				itemOdds: "1.995",
				title: "双",
				desc: "选择双数",
				actived: false,
				optionCode: "双",
			},
			{
				id: "8-5",
				itemOdds: "1.995",
				title: "选择球",
				desc: "",
				actived: false,
				optionCode: "0",
				type: SELECT_BALL,
				children: generateBalls({ length: 10, hasZero: false, startIndex: 1 }),
			},
		],
	},
	{
		id: "9",
		gamePlayName: "第八名",
		gamePlayCodes: ["smp_zhd8m", "smp_d1d10d8m"],
		desc: "投注一种属性，投注的属性与该位置的开奖号码属性相同时，即中奖<br />大小：开奖号码≥6为“大”，≤5为“小”<br />单双：开奖号码个位数为1、3、5、7、9为“单”，0、2、4、6、8为“双”<br />选球：选择1个球为1注。所选号码与该位置上的开奖号码一致，即中奖",
		actived: false,
		oddsList: [
			{
				id: "9-1",
				itemOdds: "1.995",
				title: "大",
				desc: "选择大数",
				actived: false,
				optionCode: "大",
			},
			{
				id: "9-2",
				itemOdds: "1.995",
				title: "小",
				desc: "选择小数",
				actived: false,
				optionCode: "小",
			},
			{
				id: "9-3",
				itemOdds: "1.995",
				title: "单",
				desc: "选择单数",
				actived: false,
				optionCode: "单",
			},
			{
				id: "9-4",
				itemOdds: "1.995",
				title: "双",
				desc: "选择双数",
				actived: false,
				optionCode: "双",
			},
			{
				id: "9-5",
				itemOdds: "1.995",
				title: "选择球",
				desc: "",
				actived: false,
				optionCode: "0",
				type: SELECT_BALL,
				children: generateBalls({ length: 10, hasZero: false, startIndex: 1 }),
			},
		],
	},
	{
		id: "10",
		gamePlayName: "第九名",
		gamePlayCodes: ["smp_zhd9m", "smp_d1d10d9m"],
		desc: "投注一种属性，投注的属性与该位置的开奖号码属性相同时，即中奖<br />大小：开奖号码≥6为“大”，≤5为“小”<br />单双：开奖号码个位数为1、3、5、7、9为“单”，0、2、4、6、8为“双”<br />选球：选择1个球为1注。所选号码与该位置上的开奖号码一致，即中奖",
		actived: false,
		oddsList: [
			{
				id: "10-1",
				itemOdds: "1.995",
				title: "大",
				desc: "选择大数",
				actived: false,
				optionCode: "大",
			},
			{
				id: "10-2",
				itemOdds: "1.995",
				title: "小",
				desc: "选择小数",
				actived: false,
				optionCode: "小",
			},
			{
				id: "10-3",
				itemOdds: "1.995",
				title: "单",
				desc: "选择单数",
				actived: false,
				optionCode: "单",
			},
			{
				id: "10-4",
				itemOdds: "1.995",
				title: "双",
				desc: "选择双数",
				actived: false,
				optionCode: "双",
			},
			{
				id: "10-5",
				itemOdds: "1.995",
				title: "选择球",
				desc: "",
				actived: false,
				optionCode: "0",
				type: SELECT_BALL,
				children: generateBalls({ length: 10, hasZero: false, startIndex: 1 }),
			},
		],
	},
	{
		id: "11",
		gamePlayName: "第十名",
		gamePlayCodes: ["smp_zhd10m", "smp_d1d10d10m"],
		desc: "投注一种属性，投注的属性与该位置的开奖号码属性相同时，即中奖<br />大小：开奖号码≥6为“大”，≤5为“小”<br />单双：开奖号码个位数为1、3、5、7、9为“单”，0、2、4、6、8为“双”<br />选球：选择1个球为1注。所选号码与该位置上的开奖号码一致，即中奖",
		actived: false,
		oddsList: [
			{
				id: "11-1",
				itemOdds: "1.995",
				title: "大",
				desc: "选择大数",
				actived: false,
				optionCode: "大",
			},
			{
				id: "11-2",
				itemOdds: "1.995",
				title: "小",
				desc: "选择小数",
				actived: false,
				optionCode: "小",
			},
			{
				id: "11-3",
				itemOdds: "1.995",
				title: "单",
				desc: "选择单数",
				actived: false,
				optionCode: "单",
			},
			{
				id: "11-4",
				itemOdds: "1.995",
				title: "双",
				desc: "选择双数",
				actived: false,
				optionCode: "双",
			},
			{
				id: "11-5",
				itemOdds: "1.995",
				title: "选择球",
				desc: "",
				actived: false,
				optionCode: "0",
				type: SELECT_BALL,
				children: generateBalls({ length: 10, hasZero: false, startIndex: 1 }),
			},
		],
	},
];
