/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Alert/index.vue')['default']
    Button: typeof import('./src/components/Button/Button.vue')['default']
    Carousel: typeof import('./src/components/Carousel/Carousel.vue')['default']
    CententItem: typeof import('./src/components/virtualScrollVirtualList/cententItem/cententItem.vue')['default']
    CountDown: typeof import('./src/components/CountDown/CountDown.vue')['default']
    Dialog: typeof import('./src/components/Dialog/Dialog.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FromInput: typeof import('./src/components/Input/fromInput.vue')['default']
    GameCard: typeof import('./src/components/gameCard/gameCard.vue')['default']
    H5Video: typeof import('./src/components/wVideo/h5Video.vue')['default']
    ImgSvg: typeof import('./src/components/imgSvg/imgSvg.vue')['default']
    InfiniteScroll: typeof import('./src/components/InfiniteScroll/infiniteScroll.vue')['default']
    M3u8Video: typeof import('./src/components/wVideo/m3u8Video.vue')['default']
    Mian: typeof import('./src/components/Notification/components/mian.vue')['default']
    NoneData: typeof import('./src/components/noneData/noneData.vue')['default']
    NoticeBar: typeof import('./src/components/noticeBar/index.vue')['default']
    Pagination: typeof import('./src/components/Pagination/Pagination.vue')['default']
    Popover: typeof import('./src/components/gameCard/commoments/popover/popover.vue')['default']
    RiseOrFall: typeof import('./src/components/Sport/RiseOrFall.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/Select/Select.vue')['default']
    SpinnerRoll: typeof import('./src/components/Spinner/spinner-roll.vue')['default']
    SpinnerWrap: typeof import('./src/components/Spinner/spinner-wrap.vue')['default']
    SvgIcon: typeof import('./src/components/svgIcon/index.vue')['default']
    Tabs: typeof import('./src/components/Tabs/Tabs.vue')['default']
    VirtualScrollVirtualList: typeof import('./src/components/virtualScrollVirtualList/virtualScrollVirtualList.vue')['default']
    WImage: typeof import('./src/components/wImage/wImage.vue')['default']
    WVideo: typeof import('./src/components/wVideo/wVideo.vue')['default']
  }
}
