const list = [
	{
		id: "153882",
		structCode: "smp_rx_001",
		merchantCode: "cj20203",
		itemIndex: 0,
		categoryCode: "SYXW",
		categoryName: "11选5",
		gameCode: "5FSYXW",
		gameName: "11选5",
		gamePlayCode: "smp_rx_rxy",
		gamePlayName: "任选一",
		itemType: 1,
		isEnabled: 1,
		hotFlag: 0,
		maxBonus: 0,
		totalBet: 0,
		maxBet: 10000,
		minLimit: 1,
		maxLimit: 400000,
		lang: "zh",
		gamePlayGroup: null,
		oddsPosition: "1",
		oddsList: [
			{
				id: "530546",
				merchantCode: "cj20203",
				itemIndex: 1,
				gamePlayCode: "smp_rx_rxy",
				gamePlayName: "任选一",
				optionCode: '[{"key":"至少选择1项","value":"01,02,03,04,05,06,07,08,09,10,11","minCount":1,"maxCount":0}]',
				optionName: '[{"key":"至少选择1项","value":"01,02,03,04,05,06,07,08,09,10,11"}]',
				itemOdds: "2.167",
				multiCheck: 0,
				mutualGroup: null,
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "0",
			},
		],
		multiList: null,
	},
	{
		id: "153866",
		structCode: "smp_zx_qr",
		merchantCode: "cj20203",
		itemIndex: 0,
		categoryCode: "SYXW",
		categoryName: "11选5",
		gameCode: "5FSYXW",
		gameName: "11选5",
		gamePlayCode: "smp_zx_qr",
		gamePlayName: "前二直选",
		itemType: 1,
		isEnabled: 1,
		hotFlag: 0,
		maxBonus: 0,
		totalBet: 0,
		maxBet: 10000,
		minLimit: 1,
		maxLimit: 400000,
		lang: "zh",
		gamePlayGroup: null,
		oddsPosition: "1",
		oddsList: [
			{
				id: "539439",
				merchantCode: "cj20203",
				itemIndex: 1,
				gamePlayCode: "smp_zx_qr",
				gamePlayName: "前二直选",
				optionCode:
					'[{"key":"第一球","value":"01,02,03,04,05,06,07,08,09,10,11","minCount":1,"maxCount":0},{"key":"第二球","value":"01,02,03,04,05,06,07,08,09,10,11","minCount":1,"maxCount":0}]',
				optionName: '[{"key":"第一球","value":"01,02,03,04,05,06,07,08,09,10,11"},{"key":"第二球","value":"01,02,03,04,05,06,07,08,09,10,11"}]',
				itemOdds: "108.35",
				multiCheck: 0,
				mutualGroup: null,
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "0",
			},
		],
		multiList: null,
	},
	{
		id: "153879",
		structCode: "smp_rx_002",
		merchantCode: "cj20203",
		itemIndex: 1,
		categoryCode: "SYXW",
		categoryName: "11选5",
		gameCode: "5FSYXW",
		gameName: "11选5",
		gamePlayCode: "smp_rx_rxe",
		gamePlayName: "任选二",
		itemType: 1,
		isEnabled: 1,
		hotFlag: 0,
		maxBonus: 0,
		totalBet: 0,
		maxBet: 10000,
		minLimit: 1,
		maxLimit: 400000,
		lang: "zh",
		gamePlayGroup: null,
		oddsPosition: "1",
		oddsList: [
			{
				id: "530510",
				merchantCode: "cj20203",
				itemIndex: 1,
				gamePlayCode: "smp_rx_rxe",
				gamePlayName: "任选二",
				optionCode: '[{"key":"至少选择2项","value":"01,02,03,04,05,06,07,08,09,10,11","minCount":2,"maxCount":0}]',
				optionName: '[{"key":"至少选择2项","value":"01,02,03,04,05,06,07,08,09,10,11"}]',
				itemOdds: "5.417",
				multiCheck: 0,
				mutualGroup: null,
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "0",
			},
		],
		multiList: null,
	},
	{
		id: "153865",
		structCode: "smp_zx_qs",
		merchantCode: "cj20203",
		itemIndex: 1,
		categoryCode: "SYXW",
		categoryName: "11选5",
		gameCode: "5FSYXW",
		gameName: "11选5",
		gamePlayCode: "smp_zx_qs",
		gamePlayName: "前三直选",
		itemType: 1,
		isEnabled: 1,
		hotFlag: 0,
		maxBonus: 0,
		totalBet: 0,
		maxBet: 10000,
		minLimit: 1,
		maxLimit: 400000,
		lang: "zh",
		gamePlayGroup: null,
		oddsPosition: "1",
		oddsList: [
			{
				id: "539441",
				merchantCode: "cj20203",
				itemIndex: 1,
				gamePlayCode: "smp_zx_qs",
				gamePlayName: "前三直选",
				optionCode:
					'[{"key":"第一球","value":"01,02,03,04,05,06,07,08,09,10,11","minCount":1,"maxCount":0},{"key":"第二球","value":"01,02,03,04,05,06,07,08,09,10,11","minCount":1,"maxCount":0},{"key":"第三球","value":"01,02,03,04,05,06,07,08,09,10,11","minCount":1,"maxCount":0}]',
				optionName:
					'[{"key":"第一球","value":"01,02,03,04,05,06,07,08,09,10,11"},{"key":"第二球","value":"01,02,03,04,05,06,07,08,09,10,11"},{"key":"第三球","value":"01,02,03,04,05,06,07,08,09,10,11"}]',
				itemOdds: "975.15",
				multiCheck: 0,
				mutualGroup: null,
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "0",
			},
		],
		multiList: null,
	},
	{
		id: "153872",
		structCode: "smp_sm",
		merchantCode: "cj20203",
		itemIndex: 1,
		categoryCode: "SYXW",
		categoryName: "11选5",
		gameCode: "5FSYXW",
		gameName: "11选5",
		gamePlayCode: "smp_zh_hdxdslhwdwx",
		gamePlayName: "总和",
		itemType: 1,
		isEnabled: 1,
		hotFlag: 0,
		maxBonus: 0,
		totalBet: 0,
		maxBet: 10000,
		minLimit: 1,
		maxLimit: 400000,
		lang: "zh",
		gamePlayGroup: "",
		oddsPosition: "1",
		oddsList: [
			{
				id: "537567",
				merchantCode: "cj20203",
				itemIndex: 1,
				gamePlayCode: "smp_zh_hdxdslhwdwx",
				gamePlayName: "总和",
				optionCode: "大",
				optionName: "大",
				itemOdds: "1.97",
				multiCheck: 0,
				mutualGroup: "大小互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "总和",
			},
			{
				id: "537568",
				merchantCode: "cj20203",
				itemIndex: 2,
				gamePlayCode: "smp_zh_hdxdslhwdwx",
				gamePlayName: "总和",
				optionCode: "小",
				optionName: "小",
				itemOdds: "1.97",
				multiCheck: 0,
				mutualGroup: "大小互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "总和",
			},
			{
				id: "537569",
				merchantCode: "cj20203",
				itemIndex: 3,
				gamePlayCode: "smp_zh_hdxdslhwdwx",
				gamePlayName: "总和",
				optionCode: "单",
				optionName: "单",
				itemOdds: "1.928",
				multiCheck: 0,
				mutualGroup: "单双互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "总和",
			},
			{
				id: "537570",
				merchantCode: "cj20203",
				itemIndex: 4,
				gamePlayCode: "smp_zh_hdxdslhwdwx",
				gamePlayName: "总和",
				optionCode: "双",
				optionName: "双",
				itemOdds: "2.013",
				multiCheck: 0,
				mutualGroup: "单双互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "总和",
			},
			{
				id: "537571",
				merchantCode: "cj20203",
				itemIndex: 5,
				gamePlayCode: "smp_zh_hdxdslhwdwx",
				gamePlayName: "总和",
				optionCode: "龙",
				optionName: "龙",
				itemOdds: "1.97",
				multiCheck: 0,
				mutualGroup: "龙虎互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "总和",
			},
			{
				id: "537572",
				merchantCode: "cj20203",
				itemIndex: 6,
				gamePlayCode: "smp_zh_hdxdslhwdwx",
				gamePlayName: "总和",
				optionCode: "虎",
				optionName: "虎",
				itemOdds: "1.97",
				multiCheck: 0,
				mutualGroup: "龙虎互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "总和",
			},
			{
				id: "537573",
				merchantCode: "cj20203",
				itemIndex: 7,
				gamePlayCode: "smp_zh_hdxdslhwdwx",
				gamePlayName: "总和",
				optionCode: "尾大",
				optionName: "尾大",
				itemOdds: "1.961",
				multiCheck: 0,
				mutualGroup: "尾大尾小互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "总和",
			},
			{
				id: "537574",
				merchantCode: "cj20203",
				itemIndex: 8,
				gamePlayCode: "smp_zh_hdxdslhwdwx",
				gamePlayName: "总和",
				optionCode: "尾小",
				optionName: "尾小",
				itemOdds: "1.978",
				multiCheck: 0,
				mutualGroup: "尾大尾小互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "总和",
			},
		],
		multiList: null,
	},
	{
		id: "153871",
		structCode: "smp_sm",
		merchantCode: "cj20203",
		itemIndex: 2,
		categoryCode: "SYXW",
		categoryName: "11选5",
		gameCode: "5FSYXW",
		gameName: "11选5",
		gamePlayCode: "smp_d1q",
		gamePlayName: "第一球",
		itemType: 1,
		isEnabled: 1,
		hotFlag: 0,
		maxBonus: 0,
		totalBet: 0,
		maxBet: 10000,
		minLimit: 1,
		maxLimit: 400000,
		lang: "zh",
		gamePlayGroup: null,
		oddsPosition: "1",
		oddsList: [
			{
				id: "526742",
				merchantCode: "cj20203",
				itemIndex: 1,
				gamePlayCode: "smp_d1q",
				gamePlayName: "第一球",
				optionCode: "大",
				optionName: "大",
				itemOdds: "1.97",
				multiCheck: 0,
				mutualGroup: "大小互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526743",
				merchantCode: "cj20203",
				itemIndex: 2,
				gamePlayCode: "smp_d1q",
				gamePlayName: "第一球",
				optionCode: "小",
				optionName: "小",
				itemOdds: "1.97",
				multiCheck: 0,
				mutualGroup: "大小互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526744",
				merchantCode: "cj20203",
				itemIndex: 3,
				gamePlayCode: "smp_d1q",
				gamePlayName: "第一球",
				optionCode: "单",
				optionName: "单",
				itemOdds: "1.97",
				multiCheck: 0,
				mutualGroup: "单双互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526745",
				merchantCode: "cj20203",
				itemIndex: 4,
				gamePlayCode: "smp_d1q",
				gamePlayName: "第一球",
				optionCode: "双",
				optionName: "双",
				itemOdds: "1.97",
				multiCheck: 0,
				mutualGroup: "单双互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526746",
				merchantCode: "cj20203",
				itemIndex: 5,
				gamePlayCode: "smp_d1q",
				gamePlayName: "第一球",
				optionCode: "01",
				optionName: "01",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第一球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526747",
				merchantCode: "cj20203",
				itemIndex: 6,
				gamePlayCode: "smp_d1q",
				gamePlayName: "第一球",
				optionCode: "02",
				optionName: "02",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第一球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526748",
				merchantCode: "cj20203",
				itemIndex: 7,
				gamePlayCode: "smp_d1q",
				gamePlayName: "第一球",
				optionCode: "03",
				optionName: "03",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第一球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526749",
				merchantCode: "cj20203",
				itemIndex: 8,
				gamePlayCode: "smp_d1q",
				gamePlayName: "第一球",
				optionCode: "04",
				optionName: "04",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第一球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526750",
				merchantCode: "cj20203",
				itemIndex: 9,
				gamePlayCode: "smp_d1q",
				gamePlayName: "第一球",
				optionCode: "05",
				optionName: "05",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第一球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526751",
				merchantCode: "cj20203",
				itemIndex: 10,
				gamePlayCode: "smp_d1q",
				gamePlayName: "第一球",
				optionCode: "06",
				optionName: "06",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第一球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526752",
				merchantCode: "cj20203",
				itemIndex: 11,
				gamePlayCode: "smp_d1q",
				gamePlayName: "第一球",
				optionCode: "07",
				optionName: "07",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第一球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526753",
				merchantCode: "cj20203",
				itemIndex: 12,
				gamePlayCode: "smp_d1q",
				gamePlayName: "第一球",
				optionCode: "08",
				optionName: "08",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第一球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526754",
				merchantCode: "cj20203",
				itemIndex: 13,
				gamePlayCode: "smp_d1q",
				gamePlayName: "第一球",
				optionCode: "09",
				optionName: "09",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第一球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526755",
				merchantCode: "cj20203",
				itemIndex: 14,
				gamePlayCode: "smp_d1q",
				gamePlayName: "第一球",
				optionCode: "10",
				optionName: "10",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第一球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526756",
				merchantCode: "cj20203",
				itemIndex: 15,
				gamePlayCode: "smp_d1q",
				gamePlayName: "第一球",
				optionCode: "11",
				optionName: "11",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第一球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
		],
		multiList: null,
	},
	{
		id: "153880",
		structCode: "smp_rx_003",
		merchantCode: "cj20203",
		itemIndex: 2,
		categoryCode: "SYXW",
		categoryName: "11选5",
		gameCode: "5FSYXW",
		gameName: "11选5",
		gamePlayCode: "smp_rx_rxs",
		gamePlayName: "任选三",
		itemType: 1,
		isEnabled: 1,
		hotFlag: 0,
		maxBonus: 0,
		totalBet: 0,
		maxBet: 10000,
		minLimit: 1,
		maxLimit: 400000,
		lang: "zh",
		gamePlayGroup: null,
		oddsPosition: "1",
		oddsList: [
			{
				id: "530542",
				merchantCode: "cj20203",
				itemIndex: 1,
				gamePlayCode: "smp_rx_rxs",
				gamePlayName: "任选三",
				optionCode: '[{"key":"至少选择3项","value":"01,02,03,04,05,06,07,08,09,10,11","minCount":3,"maxCount":0}]',
				optionName: '[{"key":"至少选择3项","value":"01,02,03,04,05,06,07,08,09,10,11"}]',
				itemOdds: "16.252",
				multiCheck: 0,
				mutualGroup: null,
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "0",
			},
		],
		multiList: null,
	},
	{
		id: "153869",
		structCode: "smp_sm",
		merchantCode: "cj20203",
		itemIndex: 3,
		categoryCode: "SYXW",
		categoryName: "11选5",
		gameCode: "5FSYXW",
		gameName: "11选5",
		gamePlayCode: "smp_d2q",
		gamePlayName: "第二球",
		itemType: 1,
		isEnabled: 1,
		hotFlag: 0,
		maxBonus: 0,
		totalBet: 0,
		maxBet: 10000,
		minLimit: 1,
		maxLimit: 400000,
		lang: "zh",
		gamePlayGroup: null,
		oddsPosition: "1",
		oddsList: [
			{
				id: "526847",
				merchantCode: "cj20203",
				itemIndex: 1,
				gamePlayCode: "smp_d2q",
				gamePlayName: "第二球",
				optionCode: "大",
				optionName: "大",
				itemOdds: "1.97",
				multiCheck: 0,
				mutualGroup: "大小互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526848",
				merchantCode: "cj20203",
				itemIndex: 2,
				gamePlayCode: "smp_d2q",
				gamePlayName: "第二球",
				optionCode: "小",
				optionName: "小",
				itemOdds: "1.97",
				multiCheck: 0,
				mutualGroup: "大小互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526849",
				merchantCode: "cj20203",
				itemIndex: 3,
				gamePlayCode: "smp_d2q",
				gamePlayName: "第二球",
				optionCode: "单",
				optionName: "单",
				itemOdds: "1.97",
				multiCheck: 0,
				mutualGroup: "单双互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526850",
				merchantCode: "cj20203",
				itemIndex: 4,
				gamePlayCode: "smp_d2q",
				gamePlayName: "第二球",
				optionCode: "双",
				optionName: "双",
				itemOdds: "1.97",
				multiCheck: 0,
				mutualGroup: "单双互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526851",
				merchantCode: "cj20203",
				itemIndex: 5,
				gamePlayCode: "smp_d2q",
				gamePlayName: "第二球",
				optionCode: "01",
				optionName: "01",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第二球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526852",
				merchantCode: "cj20203",
				itemIndex: 6,
				gamePlayCode: "smp_d2q",
				gamePlayName: "第二球",
				optionCode: "02",
				optionName: "02",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第二球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526853",
				merchantCode: "cj20203",
				itemIndex: 7,
				gamePlayCode: "smp_d2q",
				gamePlayName: "第二球",
				optionCode: "03",
				optionName: "03",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第二球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526854",
				merchantCode: "cj20203",
				itemIndex: 8,
				gamePlayCode: "smp_d2q",
				gamePlayName: "第二球",
				optionCode: "04",
				optionName: "04",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第二球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526855",
				merchantCode: "cj20203",
				itemIndex: 9,
				gamePlayCode: "smp_d2q",
				gamePlayName: "第二球",
				optionCode: "05",
				optionName: "05",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第二球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526856",
				merchantCode: "cj20203",
				itemIndex: 10,
				gamePlayCode: "smp_d2q",
				gamePlayName: "第二球",
				optionCode: "06",
				optionName: "06",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第二球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526857",
				merchantCode: "cj20203",
				itemIndex: 11,
				gamePlayCode: "smp_d2q",
				gamePlayName: "第二球",
				optionCode: "07",
				optionName: "07",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第二球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526858",
				merchantCode: "cj20203",
				itemIndex: 12,
				gamePlayCode: "smp_d2q",
				gamePlayName: "第二球",
				optionCode: "08",
				optionName: "08",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第二球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526859",
				merchantCode: "cj20203",
				itemIndex: 13,
				gamePlayCode: "smp_d2q",
				gamePlayName: "第二球",
				optionCode: "09",
				optionName: "09",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第二球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526860",
				merchantCode: "cj20203",
				itemIndex: 14,
				gamePlayCode: "smp_d2q",
				gamePlayName: "第二球",
				optionCode: "10",
				optionName: "10",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第二球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526861",
				merchantCode: "cj20203",
				itemIndex: 15,
				gamePlayCode: "smp_d2q",
				gamePlayName: "第二球",
				optionCode: "11",
				optionName: "11",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第二球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
		],
		multiList: null,
	},
	{
		id: "153875",
		structCode: "smp_rx_004",
		merchantCode: "cj20203",
		itemIndex: 3,
		categoryCode: "SYXW",
		categoryName: "11选5",
		gameCode: "5FSYXW",
		gameName: "11选5",
		gamePlayCode: "smp_rx_rxfour",
		gamePlayName: "任选四",
		itemType: 1,
		isEnabled: 1,
		hotFlag: 0,
		maxBonus: 0,
		totalBet: 0,
		maxBet: 10000,
		minLimit: 1,
		maxLimit: 400000,
		lang: "zh",
		gamePlayGroup: null,
		oddsPosition: "1",
		oddsList: [
			{
				id: "530522",
				merchantCode: "cj20203",
				itemIndex: 1,
				gamePlayCode: "smp_rx_rxfour",
				gamePlayName: "任选四",
				optionCode: '[{"key":"至少选择4项","value":"01,02,03,04,05,06,07,08,09,10,11","minCount":4,"maxCount":0}]',
				optionName: '[{"key":"至少选择4项","value":"01,02,03,04,05,06,07,08,09,10,11"}]',
				itemOdds: "65.01",
				multiCheck: 0,
				mutualGroup: null,
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "0",
			},
		],
		multiList: null,
	},
	{
		id: "153870",
		structCode: "smp_sm",
		merchantCode: "cj20203",
		itemIndex: 4,
		categoryCode: "SYXW",
		categoryName: "11选5",
		gameCode: "5FSYXW",
		gameName: "11选5",
		gamePlayCode: "smp_d3q",
		gamePlayName: "第三球",
		itemType: 1,
		isEnabled: 1,
		hotFlag: 0,
		maxBonus: 0,
		totalBet: 0,
		maxBet: 10000,
		minLimit: 1,
		maxLimit: 400000,
		lang: "zh",
		gamePlayGroup: null,
		oddsPosition: "1",
		oddsList: [
			{
				id: "526877",
				merchantCode: "cj20203",
				itemIndex: 1,
				gamePlayCode: "smp_d3q",
				gamePlayName: "第三球",
				optionCode: "大",
				optionName: "大",
				itemOdds: "1.97",
				multiCheck: 0,
				mutualGroup: "大小互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526878",
				merchantCode: "cj20203",
				itemIndex: 2,
				gamePlayCode: "smp_d3q",
				gamePlayName: "第三球",
				optionCode: "小",
				optionName: "小",
				itemOdds: "1.97",
				multiCheck: 0,
				mutualGroup: "大小互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526879",
				merchantCode: "cj20203",
				itemIndex: 3,
				gamePlayCode: "smp_d3q",
				gamePlayName: "第三球",
				optionCode: "单",
				optionName: "单",
				itemOdds: "1.97",
				multiCheck: 0,
				mutualGroup: "单双互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526880",
				merchantCode: "cj20203",
				itemIndex: 4,
				gamePlayCode: "smp_d3q",
				gamePlayName: "第三球",
				optionCode: "双",
				optionName: "双",
				itemOdds: "1.97",
				multiCheck: 0,
				mutualGroup: "单双互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526881",
				merchantCode: "cj20203",
				itemIndex: 5,
				gamePlayCode: "smp_d3q",
				gamePlayName: "第三球",
				optionCode: "01",
				optionName: "01",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第三球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526882",
				merchantCode: "cj20203",
				itemIndex: 6,
				gamePlayCode: "smp_d3q",
				gamePlayName: "第三球",
				optionCode: "02",
				optionName: "02",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第三球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526883",
				merchantCode: "cj20203",
				itemIndex: 7,
				gamePlayCode: "smp_d3q",
				gamePlayName: "第三球",
				optionCode: "03",
				optionName: "03",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第三球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526884",
				merchantCode: "cj20203",
				itemIndex: 8,
				gamePlayCode: "smp_d3q",
				gamePlayName: "第三球",
				optionCode: "04",
				optionName: "04",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第三球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526885",
				merchantCode: "cj20203",
				itemIndex: 9,
				gamePlayCode: "smp_d3q",
				gamePlayName: "第三球",
				optionCode: "05",
				optionName: "05",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第三球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526886",
				merchantCode: "cj20203",
				itemIndex: 10,
				gamePlayCode: "smp_d3q",
				gamePlayName: "第三球",
				optionCode: "06",
				optionName: "06",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第三球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526887",
				merchantCode: "cj20203",
				itemIndex: 11,
				gamePlayCode: "smp_d3q",
				gamePlayName: "第三球",
				optionCode: "07",
				optionName: "07",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第三球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526888",
				merchantCode: "cj20203",
				itemIndex: 12,
				gamePlayCode: "smp_d3q",
				gamePlayName: "第三球",
				optionCode: "08",
				optionName: "08",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第三球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526889",
				merchantCode: "cj20203",
				itemIndex: 13,
				gamePlayCode: "smp_d3q",
				gamePlayName: "第三球",
				optionCode: "09",
				optionName: "09",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第三球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526890",
				merchantCode: "cj20203",
				itemIndex: 14,
				gamePlayCode: "smp_d3q",
				gamePlayName: "第三球",
				optionCode: "10",
				optionName: "10",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第三球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "526891",
				merchantCode: "cj20203",
				itemIndex: 15,
				gamePlayCode: "smp_d3q",
				gamePlayName: "第三球",
				optionCode: "11",
				optionName: "11",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第三球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
		],
		multiList: null,
	},
	{
		id: "153878",
		structCode: "smp_rx_005",
		merchantCode: "cj20203",
		itemIndex: 4,
		categoryCode: "SYXW",
		categoryName: "11选5",
		gameCode: "5FSYXW",
		gameName: "11选5",
		gamePlayCode: "smp_rx_rxfive",
		gamePlayName: "任选五",
		itemType: 1,
		isEnabled: 1,
		hotFlag: 0,
		maxBonus: 0,
		totalBet: 0,
		maxBet: 10000,
		minLimit: 1,
		maxLimit: 400000,
		lang: "zh",
		gamePlayGroup: null,
		oddsPosition: "1",
		oddsList: [
			{
				id: "530518",
				merchantCode: "cj20203",
				itemIndex: 1,
				gamePlayCode: "smp_rx_rxfive",
				gamePlayName: "任选五",
				optionCode: '[{"key":"至少选择5项","value":"01,02,03,04,05,06,07,08,09,10,11","minCount":5,"maxCount":0}]',
				optionName: '[{"key":"至少选择5项","value":"01,02,03,04,05,06,07,08,09,10,11"}]',
				itemOdds: "455.07",
				multiCheck: 0,
				mutualGroup: null,
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "0",
			},
		],
		multiList: null,
	},
	{
		id: "153876",
		structCode: "smp_rx_065",
		merchantCode: "cj20203",
		itemIndex: 5,
		categoryCode: "SYXW",
		categoryName: "11选5",
		gameCode: "5FSYXW",
		gameName: "11选5",
		gamePlayCode: "smp_rx_rxlzw",
		gamePlayName: "任选六中五",
		itemType: 1,
		isEnabled: 1,
		hotFlag: 0,
		maxBonus: 0,
		totalBet: 0,
		maxBet: 10000,
		minLimit: 1,
		maxLimit: 400000,
		lang: "zh",
		gamePlayGroup: null,
		oddsPosition: "1",
		oddsList: [
			{
				id: "530530",
				merchantCode: "cj20203",
				itemIndex: 1,
				gamePlayCode: "smp_rx_rxlzw",
				gamePlayName: "任选六中五",
				optionCode: '[{"key":"至少选择6项","value":"01,02,03,04,05,06,07,08,09,10,11","minCount":6,"maxCount":0}]',
				optionName: '[{"key":"至少选择6项","value":"01,02,03,04,05,06,07,08,09,10,11"}]',
				itemOdds: "75.844",
				multiCheck: 0,
				mutualGroup: null,
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "0",
			},
		],
		multiList: null,
	},
	{
		id: "153867",
		structCode: "smp_sm",
		merchantCode: "cj20203",
		itemIndex: 5,
		categoryCode: "SYXW",
		categoryName: "11选5",
		gameCode: "5FSYXW",
		gameName: "11选5",
		gamePlayCode: "smp_d4q",
		gamePlayName: "第四球",
		itemType: 1,
		isEnabled: 1,
		hotFlag: 0,
		maxBonus: 0,
		totalBet: 0,
		maxBet: 10000,
		minLimit: 1,
		maxLimit: 400000,
		lang: "zh",
		gamePlayGroup: null,
		oddsPosition: "1",
		oddsList: [
			{
				id: "527012",
				merchantCode: "cj20203",
				itemIndex: 1,
				gamePlayCode: "smp_d4q",
				gamePlayName: "第四球",
				optionCode: "大",
				optionName: "大",
				itemOdds: "1.97",
				multiCheck: 0,
				mutualGroup: "大小互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527013",
				merchantCode: "cj20203",
				itemIndex: 2,
				gamePlayCode: "smp_d4q",
				gamePlayName: "第四球",
				optionCode: "小",
				optionName: "小",
				itemOdds: "1.97",
				multiCheck: 0,
				mutualGroup: "大小互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527014",
				merchantCode: "cj20203",
				itemIndex: 3,
				gamePlayCode: "smp_d4q",
				gamePlayName: "第四球",
				optionCode: "单",
				optionName: "单",
				itemOdds: "1.97",
				multiCheck: 0,
				mutualGroup: "单双互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527015",
				merchantCode: "cj20203",
				itemIndex: 4,
				gamePlayCode: "smp_d4q",
				gamePlayName: "第四球",
				optionCode: "双",
				optionName: "双",
				itemOdds: "1.97",
				multiCheck: 0,
				mutualGroup: "单双互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527016",
				merchantCode: "cj20203",
				itemIndex: 5,
				gamePlayCode: "smp_d4q",
				gamePlayName: "第四球",
				optionCode: "01",
				optionName: "01",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第四球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527017",
				merchantCode: "cj20203",
				itemIndex: 6,
				gamePlayCode: "smp_d4q",
				gamePlayName: "第四球",
				optionCode: "02",
				optionName: "02",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第四球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527018",
				merchantCode: "cj20203",
				itemIndex: 7,
				gamePlayCode: "smp_d4q",
				gamePlayName: "第四球",
				optionCode: "03",
				optionName: "03",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第四球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527019",
				merchantCode: "cj20203",
				itemIndex: 8,
				gamePlayCode: "smp_d4q",
				gamePlayName: "第四球",
				optionCode: "04",
				optionName: "04",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第四球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527020",
				merchantCode: "cj20203",
				itemIndex: 9,
				gamePlayCode: "smp_d4q",
				gamePlayName: "第四球",
				optionCode: "05",
				optionName: "05",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第四球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527021",
				merchantCode: "cj20203",
				itemIndex: 10,
				gamePlayCode: "smp_d4q",
				gamePlayName: "第四球",
				optionCode: "06",
				optionName: "06",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第四球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527022",
				merchantCode: "cj20203",
				itemIndex: 11,
				gamePlayCode: "smp_d4q",
				gamePlayName: "第四球",
				optionCode: "07",
				optionName: "07",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第四球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527023",
				merchantCode: "cj20203",
				itemIndex: 12,
				gamePlayCode: "smp_d4q",
				gamePlayName: "第四球",
				optionCode: "08",
				optionName: "08",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第四球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527024",
				merchantCode: "cj20203",
				itemIndex: 13,
				gamePlayCode: "smp_d4q",
				gamePlayName: "第四球",
				optionCode: "09",
				optionName: "09",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第四球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527025",
				merchantCode: "cj20203",
				itemIndex: 14,
				gamePlayCode: "smp_d4q",
				gamePlayName: "第四球",
				optionCode: "10",
				optionName: "10",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第四球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527026",
				merchantCode: "cj20203",
				itemIndex: 15,
				gamePlayCode: "smp_d4q",
				gamePlayName: "第四球",
				optionCode: "11",
				optionName: "11",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第四球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
		],
		multiList: null,
	},
	{
		id: "153881",
		structCode: "smp_rx_075",
		merchantCode: "cj20203",
		itemIndex: 6,
		categoryCode: "SYXW",
		categoryName: "11选5",
		gameCode: "5FSYXW",
		gameName: "11选5",
		gamePlayCode: "smp_rx_rxqzw",
		gamePlayName: "任选七中五",
		itemType: 1,
		isEnabled: 1,
		hotFlag: 0,
		maxBonus: 0,
		totalBet: 0,
		maxBet: 10000,
		minLimit: 1,
		maxLimit: 400000,
		lang: "zh",
		gamePlayGroup: null,
		oddsPosition: "1",
		oddsList: [
			{
				id: "530534",
				merchantCode: "cj20203",
				itemIndex: 1,
				gamePlayCode: "smp_rx_rxqzw",
				gamePlayName: "任选七中五",
				optionCode: '[{"key":"至少选择7项","value":"01,02,03,04,05,06,07,08,09,10,11","minCount":7,"maxCount":0}]',
				optionName: '[{"key":"至少选择7项","value":"01,02,03,04,05,06,07,08,09,10,11"}]',
				itemOdds: "21.67",
				multiCheck: 0,
				mutualGroup: null,
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "0",
			},
		],
		multiList: null,
	},
	{
		id: "153868",
		structCode: "smp_sm",
		merchantCode: "cj20203",
		itemIndex: 6,
		categoryCode: "SYXW",
		categoryName: "11选5",
		gameCode: "5FSYXW",
		gameName: "11选5",
		gamePlayCode: "smp_d5q",
		gamePlayName: "第五球",
		itemType: 1,
		isEnabled: 1,
		hotFlag: 0,
		maxBonus: 0,
		totalBet: 0,
		maxBet: 10000,
		minLimit: 1,
		maxLimit: 400000,
		lang: "zh",
		gamePlayGroup: null,
		oddsPosition: "1",
		oddsList: [
			{
				id: "527117",
				merchantCode: "cj20203",
				itemIndex: 1,
				gamePlayCode: "smp_d5q",
				gamePlayName: "第五球",
				optionCode: "大",
				optionName: "大",
				itemOdds: "1.97",
				multiCheck: 0,
				mutualGroup: "大小互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527118",
				merchantCode: "cj20203",
				itemIndex: 2,
				gamePlayCode: "smp_d5q",
				gamePlayName: "第五球",
				optionCode: "小",
				optionName: "小",
				itemOdds: "1.97",
				multiCheck: 0,
				mutualGroup: "大小互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527119",
				merchantCode: "cj20203",
				itemIndex: 3,
				gamePlayCode: "smp_d5q",
				gamePlayName: "第五球",
				optionCode: "单",
				optionName: "单",
				itemOdds: "1.97",
				multiCheck: 0,
				mutualGroup: "单双互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527120",
				merchantCode: "cj20203",
				itemIndex: 4,
				gamePlayCode: "smp_d5q",
				gamePlayName: "第五球",
				optionCode: "双",
				optionName: "双",
				itemOdds: "1.97",
				multiCheck: 0,
				mutualGroup: "单双互斥",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527121",
				merchantCode: "cj20203",
				itemIndex: 5,
				gamePlayCode: "smp_d5q",
				gamePlayName: "第五球",
				optionCode: "01",
				optionName: "01",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第五球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527122",
				merchantCode: "cj20203",
				itemIndex: 6,
				gamePlayCode: "smp_d5q",
				gamePlayName: "第五球",
				optionCode: "02",
				optionName: "02",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第五球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527123",
				merchantCode: "cj20203",
				itemIndex: 7,
				gamePlayCode: "smp_d5q",
				gamePlayName: "第五球",
				optionCode: "03",
				optionName: "03",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第五球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527124",
				merchantCode: "cj20203",
				itemIndex: 8,
				gamePlayCode: "smp_d5q",
				gamePlayName: "第五球",
				optionCode: "04",
				optionName: "04",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第五球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527125",
				merchantCode: "cj20203",
				itemIndex: 9,
				gamePlayCode: "smp_d5q",
				gamePlayName: "第五球",
				optionCode: "05",
				optionName: "05",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第五球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527126",
				merchantCode: "cj20203",
				itemIndex: 10,
				gamePlayCode: "smp_d5q",
				gamePlayName: "第五球",
				optionCode: "06",
				optionName: "06",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第五球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527127",
				merchantCode: "cj20203",
				itemIndex: 11,
				gamePlayCode: "smp_d5q",
				gamePlayName: "第五球",
				optionCode: "07",
				optionName: "07",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第五球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527128",
				merchantCode: "cj20203",
				itemIndex: 12,
				gamePlayCode: "smp_d5q",
				gamePlayName: "第五球",
				optionCode: "08",
				optionName: "08",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第五球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527129",
				merchantCode: "cj20203",
				itemIndex: 13,
				gamePlayCode: "smp_d5q",
				gamePlayName: "第五球",
				optionCode: "09",
				optionName: "09",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第五球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527130",
				merchantCode: "cj20203",
				itemIndex: 14,
				gamePlayCode: "smp_d5q",
				gamePlayName: "第五球",
				optionCode: "10",
				optionName: "10",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第五球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
			{
				id: "527131",
				merchantCode: "cj20203",
				itemIndex: 15,
				gamePlayCode: "smp_d5q",
				gamePlayName: "第五球",
				optionCode: "11",
				optionName: "11",
				itemOdds: "10.835",
				multiCheck: 0,
				mutualGroup: "第五球",
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "",
			},
		],
		multiList: null,
	},
	{
		id: "153877",
		structCode: "smp_rx_085",
		merchantCode: "cj20203",
		itemIndex: 7,
		categoryCode: "SYXW",
		categoryName: "11选5",
		gameCode: "5FSYXW",
		gameName: "11选5",
		gamePlayCode: "smp_rx_rxbzw",
		gamePlayName: "任选八中五",
		itemType: 1,
		isEnabled: 1,
		hotFlag: 0,
		maxBonus: 0,
		totalBet: 0,
		maxBet: 10000,
		minLimit: 1,
		maxLimit: 400000,
		lang: "zh",
		gamePlayGroup: null,
		oddsPosition: "1",
		oddsList: [
			{
				id: "530506",
				merchantCode: "cj20203",
				itemIndex: 1,
				gamePlayCode: "smp_rx_rxbzw",
				gamePlayName: "任选八中五",
				optionCode: '[{"key":"至少选择8项","value":"01,02,03,04,05,06,07,08,09,10,11","minCount":8,"maxCount":0}]',
				optionName: '[{"key":"至少选择8项","value":"01,02,03,04,05,06,07,08,09,10,11"}]',
				itemOdds: "8.126",
				multiCheck: 0,
				mutualGroup: null,
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "0",
			},
		],
		multiList: null,
	},
	{
		id: "153873",
		structCode: "smp_rx_095",
		merchantCode: "cj20203",
		itemIndex: 8,
		categoryCode: "SYXW",
		categoryName: "11选5",
		gameCode: "5FSYXW",
		gameName: "11选5",
		gamePlayCode: "smp_rx_qrzx",
		gamePlayName: "前二组选",
		itemType: 1,
		isEnabled: 1,
		hotFlag: 0,
		maxBonus: 0,
		totalBet: 0,
		maxBet: 10000,
		minLimit: 1,
		maxLimit: 400000,
		lang: "zh",
		gamePlayGroup: null,
		oddsPosition: "1",
		oddsList: [
			{
				id: "530494",
				merchantCode: "cj20203",
				itemIndex: 1,
				gamePlayCode: "smp_rx_qrzx",
				gamePlayName: "前二组选",
				optionCode: '[{"key":"至少选择2项","value":"01,02,03,04,05,06,07,08,09,10,11","minCount":2,"maxCount":0}]',
				optionName: '[{"key":"至少选择2项","value":"01,02,03,04,05,06,07,08,09,10,11"}]',
				itemOdds: "54.175",
				multiCheck: 0,
				mutualGroup: null,
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "0",
			},
		],
		multiList: null,
	},
	{
		id: "153874",
		structCode: "smp_rx_096",
		merchantCode: "cj20203",
		itemIndex: 9,
		categoryCode: "SYXW",
		categoryName: "11选5",
		gameCode: "5FSYXW",
		gameName: "11选5",
		gamePlayCode: "smp_rx_qszx",
		gamePlayName: "前三组选",
		itemType: 1,
		isEnabled: 1,
		hotFlag: 0,
		maxBonus: 0,
		totalBet: 0,
		maxBet: 10000,
		minLimit: 1,
		maxLimit: 400000,
		lang: "zh",
		gamePlayGroup: null,
		oddsPosition: "1",
		oddsList: [
			{
				id: "530498",
				merchantCode: "cj20203",
				itemIndex: 1,
				gamePlayCode: "smp_rx_qszx",
				gamePlayName: "前三组选",
				optionCode: '[{"key":"至少选择3项","value":"01,02,03,04,05,06,07,08,09,10,11","minCount":3,"maxCount":0}]',
				optionName: '[{"key":"至少选择3项","value":"01,02,03,04,05,06,07,08,09,10,11"}]',
				itemOdds: "162.525",
				multiCheck: 0,
				mutualGroup: null,
				gameCode: "5FSYXW",
				categoryCode: "SYXW",
				itemType: null,
				isEnabled: 1,
				lang: "zh",
				optionGroup: "0",
			},
		],
		multiList: null,
	},
];
